frr defaults traditional
hostname r3
!
interface eth1
 ip address 192.168.23.3/30
!
interface lo
 ip address 3.3.3.3/24
!
router bgp 300
 neighbor 192.168.23.2 remote-as 200
 !
 address-family ipv4 unicast
  network 3.3.3.0/24
  neighbor 192.168.23.2 route-map ALLOW-ALL in
  neighbor 192.168.23.2 route-map ALLOW-ALL out
 exit-address-family
!
ip prefix-list ALLOW seq 5 permit 0.0.0.0/0 le 32
!
route-map ALLOW-ALL permit 10
 match ip address prefix-list ALLOW
!
