frr defaults traditional
hostname r1
!
interface eth1
 ip address 192.168.12.1/30
!
interface lo
 ip address 1.1.1.1/24
!
router bgp 100
 neighbor 192.168.12.2 remote-as 200
 !
 address-family ipv4 unicast
  network 1.1.1.0/24
  neighbor 192.168.12.2 route-map ALLOW-ALL in
  neighbor 192.168.12.2 route-map ALLOW-ALL out
 exit-address-family
!
ip prefix-list ALLOW seq 5 permit 0.0.0.0/0 le 32
!
route-map ALLOW-ALL permit 10
 match ip address prefix-list ALLOW
!
