frr defaults traditional
hostname r2
!
interface eth1
 ip address 192.168.12.2/30
!
interface lo
 ip address 2.2.2.2/24
!
router bgp 200
 neighbor 192.168.12.1 remote-as 100
 !
 address-family ipv4 unicast
  network 2.2.2.0/24
  neighbor 192.168.12.1 route-map ALLOW-ALL in
  neighbor 192.168.12.1 route-map ALLOW-ALL out
 exit-address-family
!
ip prefix-list ALLOW seq 5 permit 0.0.0.0/0 le 32
!
route-map ALLOW-ALL permit 10
 match ip address prefix-list ALLOW
!
